name: Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download bpftool
        run: |
          curl -L https://github.com/libbpf/bpftool/releases/download/v7.4.0/bpftool-v7.4.0-amd64.tar.gz \
            | tar -xz
          chmod +x bpftool
          mv bpftool bpftool_bin

      - name: Build Docker image
        run: docker build -t injector-builder .

      - name: Build project
        run: |
          docker run --rm \
            -v "$PWD:/work" \
            -w /work \
            injector-builder \
            make

      - name: Verify output
        run: |
          ls -lah
          test -f injector

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: injector
          path: injector

      - name: Generate tag
        id: tag
        run: |
          TAG="v1.0.${{ github.run_number }}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git tag "${{ steps.tag.outputs.tag }}"
          git push origin "${{ steps.tag.outputs.tag }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          generate_release_notes: true
          files: |
            injector
